import io
import os
import platform
from PIL import Image, ImageDraw, ImageFont

from nonebot import on_command
from nonebot.adapters import Event
from nonebot.adapters.onebot.v11 import Message, MessageSegment
from nonebot.exception import FinishedException

chuhelp_cmd = on_command("chuhelp", priority=5, block=True)

def get_font(size, weight="Normal"):
    try:
        if platform.system() == "Windows":
            return ImageFont.truetype("msyh.ttc", size)
        else:
            font_paths = [
                f"/usr/share/fonts/opentype/SourceHanSans/SourceHanSansSC-{weight}.otf",
                f"/usr/share/fonts/opentype/noto/NotoSansCJK-{weight}.ttc",
                "/usr/share/fonts/wqy-microhei/wqy-microhei.ttc"
            ]
            for p in font_paths:
                if os.path.exists(p): return ImageFont.truetype(p, size)
            return ImageFont.load_default()
    except: return ImageFont.load_default()

def draw_help():
    width = 800
    img = Image.new("RGB", (width, 10), (30, 30, 46))
    draw = ImageDraw.Draw(img)

    font_title = get_font(48, "Bold")
    font_cmd = get_font(28, "Bold")
    font_desc = get_font(22, "Normal")

    commands = [
        ("[1] /bind [好友码]  （若QQ号绑定过lxns查分器则可不用bind）", "绑定至lxns查分器"),
        ("[2] /chuupdate", "上传 lxns 导出的分数 CSV 或者rin导出的json 更新本地成绩"),
        ("[3] /chulist [查询条件] [--nocat]", "生成由多种条件组合查询的 Overpower 统计图。\n支持：定数、难度、版本、以及部分特殊指定分类。\n多个条件间可用空格叠加取交集。\n含 --nocat 标志时将不再按定数分组，而是汇总按分数排行。\n示例: /chulist 13+ sun 车万 --nocat"),
        ("[4] /chuinfo", "获取当前绑定账号信息"),
        ("[5] [曲名/别名/ID]是什么歌", "查询目标歌曲详情信息"),
        ("[6] /添加别名 [ID] [别名]", "为歌曲添加自定义本地别名"),
        ("[7] /查看别名 [模糊查询/id]", "查看指定曲目的所有别名"),
        ("[8] /查剧情 [角色名/关键词]", "搜索并阅读指定角色的剧情"),
        ("[9] /随机剧情", "随机抽选一段角色剧情阅读"),
        ("[10] /剧情列表", "查看当前已收录剧情的所有角色列表")
    ]
    
    y = 140
    for cmd, desc in commands:
        y += 45
        for line in desc.split('\n'):
            y += 35
        y += 20
        
    height = y + 80
    img = Image.new("RGB", (width, height), (30, 30, 46))
    draw = ImageDraw.Draw(img)
    
    draw.text((40, 40), "Unibot 基础指令", font=font_title, fill=(248, 248, 242))
    draw.line([(40, 110), (width - 40, 110)], fill=(98, 114, 164), width=2)

    y = 140
    for cmd, desc in commands:
        draw.text((40, y), cmd, font=font_cmd, fill=(255, 121, 198))
        y += 45
        for line in desc.split('\n'):
            draw.text((60, y), line, font=font_desc, fill=(139, 233, 253))
            y += 35
        y += 20
        
    draw.line([(40, y + 10), (width - 40, y + 10)], fill=(98, 114, 164), width=2)
    font_footer = get_font(18, "Normal")
    draw.text((40, y + 30), "Generated by Robinbot | unibot", font=font_footer, fill=(191, 191, 191))
    
    buf = io.BytesIO()
    img.save(buf, format="PNG")
    return buf.getvalue()

@chuhelp_cmd.handle()
async def _(event: Event):
    try:
        img_bytes = draw_help()
        await chuhelp_cmd.finish(MessageSegment.image(img_bytes))
    except FinishedException:
        raise
    except Exception as e:
        await chuhelp_cmd.finish(f"生成帮助图片失败: {e}")